### ISSUE TITLE
Default length of private key for --type=rsa

### ISSUE THREAD

**Issue by MartinMartimeo** [Gibheer/pkictl#3]
Should not be 512.

**Comment by j0holo** [comment]
But the default is already 1024, https://github.com/Gibheer/pkictl/blob/master/create_private_key.go#L15

Still not great, but 2048 should be the minimum default.

**Comment by j0holo** [comment]
I can create a PR tomorrow @Gibheer @MartinMartimeo if you want. But that takes maybe more time to approve then to push it yourself. XD

**Comment by Gibheer** [comment]
Ah, sorry. Didn't see  that comment sadly :( If you want, you can create a pull request :) And yes, 1024 as the default is a bit on the low side. Maybe setting it to 4096 would be better.

**Comment by Gibheer** [comment]
Thank you for fixing the issue :)
